/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tl_jdbc;

import java.io.File;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nducmd
 */
public class SinhVienFrame extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public SinhVienFrame() {
        initComponents();
        model = (DefaultTableModel) Bang.getModel();
        model.setRowCount(0);
        idField.setEditable(false);
    }
    private ArrayList<SinhVien> svList = new ArrayList<>();
    private DefaultTableModel model;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Bang = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        displayButton = new javax.swing.JButton();
        idField = new javax.swing.JTextField();
        tenField = new javax.swing.JTextField();
        lopField = new javax.swing.JTextField();
        gpaField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        msg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Thông tin sinh viên");

        Bang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã", "Tên", "Lớp", "GPA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Bang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Bang);

        addButton.setText("Thêm");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Cập nhật");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Xoá");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        displayButton.setText("Hiển thị");
        displayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayButtonActionPerformed(evt);
            }
        });

        lopField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lopFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã:");

        jLabel3.setText("Lớp:");

        jLabel4.setText("Tên:");

        jLabel5.setText("Điểm:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(418, 418, 418))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lopField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(displayButton)
                                .addGap(18, 18, 18)
                                .addComponent(addButton)
                                .addGap(30, 30, 30)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateButton)
                                .addGap(18, 18, 18)
                                .addComponent(deleteButton)
                                .addGap(18, 18, 18)
                                .addComponent(resetButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tenField, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                    .addComponent(gpaField))
                                .addGap(297, 297, 297))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(msg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(updateButton)
                    .addComponent(deleteButton)
                    .addComponent(displayButton)
                    .addComponent(resetButton))
                .addGap(9, 9, 9)
                .addComponent(msg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lopField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(gpaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String query = "INSERT INTO sinhvien (ho_ten, lop, gpa) VALUES (?, ?, ?)";
        //SinhVien tmp = new SinhVien(tenField.getText(), lopField.getText(), gpaField.getText());
        if (tenField.getText().equals("") || 
                lopField.getText().equals("")||
                gpaField.getText().equals("")) {
            msg.setText("Vui Long Dien Du Thong Tin");
            return;
        }
        try (Connection connection = Database.connectDB(); PreparedStatement preparedStatement = connection.prepareStatement(query)) {

            preparedStatement.setString(1, tenField.getText());
            preparedStatement.setString(2, lopField.getText());
            preparedStatement.setDouble(3, Double.parseDouble(gpaField.getText()));

            int rowsAffected = preparedStatement.executeUpdate();
            clearField();
            msg.setText("Them Thanh Cong");
            clearField();
            svList.clear();
            svList.addAll(getFullSV());
            model.setRowCount(0);
            for (SinhVien sv : svList) {
                model.addRow(sv.toObject());
            }
        } catch (SQLException ex) {
            Logger.getLogger(SinhVienFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_addButtonActionPerformed
    private ArrayList<SinhVien> getFullSV() {
        ArrayList<SinhVien> tmp = new ArrayList<>();
        String query = "SELECT * FROM sinhvien";
        try (Connection connection = Database.connectDB(); Statement statement = connection.createStatement()) {

            ResultSet resultSet = statement.executeQuery(query);

            while (resultSet.next()) {
                svList.add(new SinhVien(resultSet.getInt("id_sv"),
                        resultSet.getString("ho_ten"),
                        resultSet.getString("lop"),
                        resultSet.getDouble("gpa")));
            }
            // Đóng kết nối
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return tmp;
    }
    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        if (tenField.getText().equals("") || 
                lopField.getText().equals("")||
                gpaField.getText().equals("") ||
                idField.getText().equals("")) {
            msg.setText("Vui Long Dien Du Thong Tin");
            return;
        }
        String query = "UPDATE sinhvien SET ho_ten = ?, lop = ?, gpa = ? WHERE id_sv = ?";
        try (Connection connection = Database.connectDB(); PreparedStatement preparedStatement = connection.prepareStatement(query)) {
            preparedStatement.setString(1, tenField.getText());
            preparedStatement.setString(2, lopField.getText());
            preparedStatement.setFloat(3, Float.parseFloat(gpaField.getText()));
            preparedStatement.setInt(4, Integer.parseInt(idField.getText()));

            int rowsAffected = preparedStatement.executeUpdate();
            msg.setText("Sua Thanh Cong");
            clearField();
            svList.clear();
            svList.addAll(getFullSV());
            model.setRowCount(0);
            for (SinhVien sv : svList) {
                model.addRow(sv.toObject());
            }
        } catch (Exception e) {
            e.printStackTrace();

        }
    }//GEN-LAST:event_updateButtonActionPerformed
    private void clearField() {
        idField.setText("");
        tenField.setText("");
        lopField.setText("");
        gpaField.setText("");
    }
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        
        
        if (idField.getText().equals("")) {
            msg.setText("Vui Long Chon Sinh Vien");
            return;
        }
        String query = "DELETE FROM sinhvien WHERE id_sv = ?";
        
        try (Connection connection = Database.connectDB();
             PreparedStatement preparedStatement = connection.prepareStatement(query)) {
            
            preparedStatement.setInt(1, Integer.parseInt(idField.getText()));
            
            int rowsAffected = preparedStatement.executeUpdate();
            msg.setText("Xoa Thanh Cong");
            clearField();
            svList.clear();
            svList.addAll(getFullSV());
            model.setRowCount(0);
            for (SinhVien sv : svList) {
                model.addRow(sv.toObject());
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        

    }//GEN-LAST:event_deleteButtonActionPerformed

    private void displayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayButtonActionPerformed
        // TODO add your handling code here:
        svList.clear();
        svList.addAll(getFullSV());
        model.setRowCount(0);
        for (SinhVien sv : svList) {
            model.addRow(sv.toObject());
        }
    }//GEN-LAST:event_displayButtonActionPerformed

    private void BangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BangMouseClicked
        // TODO add your handling code here:
        int selectedRow = Bang.getSelectedRow();
        if (selectedRow != -1) {
            // Get data from the selected row
            Object ma = Bang.getValueAt(selectedRow, 0);
            Object ten = Bang.getValueAt(selectedRow, 1);
            Object lop = Bang.getValueAt(selectedRow, 2);
            Object gpa = Bang.getValueAt(selectedRow, 3);
            System.out.println(ma.toString());
            idField.setText(ma.toString());
            tenField.setText(ten.toString());
            lopField.setText(lop.toString());
            gpaField.setText(gpa.toString());
            // Update text fields with selected data
//            textField1.setText(firstName.toString());
//            textField2.setText(lastName.toString());
        }
    }//GEN-LAST:event_BangMouseClicked

    private void lopFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lopFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lopFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinhVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinhVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinhVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinhVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SinhVienFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Bang;
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton displayButton;
    private javax.swing.JTextField gpaField;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lopField;
    private javax.swing.JLabel msg;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField tenField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
